# Michelle Tagarino
# makefile for the dictionary program (Assignment #1)

dictionary1 : dictionary1.o
		g++ dictionary1.o -o dictionary1


dictionary1.o : dictionary1.cpp
		g++ -c dictionary1.cpp

clean:
		rm *.o dictionary1
